[package]

name = "Tone Generator"
version = "0.2.0"
authors = [ "Ryan Drew <rsdrew@gmail.com>" ]

[[bin]]

name = "tonegen"

[dependencies.wavfile]
path = "src/wavfile"

[dependencies]
rand = "0.3"
getopts = "0.2"