[package]

name = "Tone Generator"
version = "0.1.0"
authors = [ "Ryan Drew <rsdrew@gmail.com>" ]

[[bin]]

name = "tonegen"

[dependencies.wavout]
path = "src/wavefile"

[dependencies]
rand = "0.3"
